

source=~/.cache/wal/hyprland.conf
source=~/.config/hypr/monitors.conf
source=~/.config/hypr/localvars.conf
source=~/.config/hypr/autostart.conf
source=~/.config/hypr/envvars.conf
source=~/.config/hypr/input.conf
source=~/.config/hypr/look.conf
source=~/.config/hypr/windowrules.conf
source=~/.config/hypr/keybindings.conf


dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}


