
source = ~/.config/hypr/hyprland/monitors.conf
source = ~/.config/hypr/hyprland/input.conf

source = ~/.config/hypr/hyprland/envs.conf

source = ~/.config/hypr/hyprland/programs.conf
source = ~/.config/hypr/hyprland/autostart.conf

source = ~/.config/hypr/hyprland/keybinds.conf

source = ~/.config/hypr/hyprland/rules.conf
source = ~/.config/hypr/hyprland/decorations.conf
source = ~/.config/hypr/hyprland/layout.conf
