
#################
### AUTOSTART ###
#################

exec-once = swww-daemon
exec-once =
exec-once =

### sudo pacman -S noto-fonts noto-fonts-emoji noto-fonts-extra noto-fonts-cjk ttf-nerd-fonts-symbols ttf-font-awesome
