
#############
### INPUT ###
#############

input {
    kb_layout = us, ru
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =
    repeat_delay = 300

    sensitivity = 0
    follow_mouse = 1

    touchpad {
        disable_while_typing = true
        natural_scroll = true
    }
}
