include /home/dallix/.cache/wal/colors-kitty.conf

### font
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13.0

confirm_os_window_close 0
window_padding_width 5 12


### cursor
cursor_shape beam
cursor_shape_unfocused beam
cursor_beam_thickness 1.5
cursor_trail 1
cursor_trail_decay 0.2 0.3

# foreground #dddddd
# background #000000

background_opacity 0.67
